# Generated by Django 4.2.6 on 2023-10-27 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peminjamanbuku', '0003_peminjamanbuku_img_buku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamanbuku',
            name='img_buku',
        ),
    ]
