# Generated by Django 4.2.6 on 2023-10-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjamanbuku', '0004_remove_peminjamanbuku_img_buku'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamanbuku',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
