# Generated by Django 4.2.6 on 2023-10-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjamanbuku', '0007_peminjamanbuku_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peminjamanbuku',
            name='img',
        ),
        migrations.AddField(
            model_name='peminjamanbuku',
            name='gambarBuku',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
