# Generated by Django 4.2.6 on 2023-10-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peminjamanbuku', '0008_remove_peminjamanbuku_img_peminjamanbuku_gambarbuku'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminjamanbuku',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
