# Generated by Django 4.2.7 on 2023-12-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftarbuku', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
