# Generated by Django 5.0 on 2023-12-09 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_thread_forum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='author',
            new_name='user',
        ),
    ]
