# Generated by Django 4.2.6 on 2023-10-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='date_updated',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='user',
        ),
    ]
