# Generated by Django 4.2.6 on 2023-10-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_forum_date_updated_remove_forum_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
    ]
