# Generated by Django 5.0 on 2023-12-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_author_thread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
