# Generated by Django 4.2.6 on 2023-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_rename_user_thread_author_alter_thread_forum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.CharField(choices=[('thread', 'Thread Baru'), ('recommend', 'Thread Rekomendasi Buku'), ('penulis', 'Thread Penulis')], default='', max_length=9),
        ),
    ]
