# Generated by Django 4.2.6 on 2023-10-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_alter_buku_isbn'),
        ('forum', '0005_alter_thread_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buku.buku'),
        ),
    ]
