# Generated by Django 4.2.6 on 2023-10-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_thread_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='book',
            new_name='buku',
        ),
    ]
