# Generated by Django 4.2.6 on 2023-10-29 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_rename_book_thread_buku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='forum',
            field=models.CharField(choices=[('thread', 'Thread Baru'), ('recommend', 'Thread Rekomendasi Buku'), ('penulis', 'Thread Penulis')], default='thread', max_length=9, null=True),
        ),
    ]
