# Generated by Django 4.2.6 on 2023-10-26 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempatBaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tempat', models.IntegerField(unique=True)),
                ('dipesan', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('durasi', models.DurationField()),
                ('buku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buku.buku')),
                ('tempat_baca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservasi.tempatbaca')),
            ],
        ),
    ]
