# Generated by Django 4.2.6 on 2023-10-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasi',
            old_name='durasi',
            new_name='durasi_baca',
        ),
    ]
