# Generated by Django 4.2.6 on 2023-10-27 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservasi', '0002_rename_durasi_reservasi_durasi_baca'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='jam',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='tanggal',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reservasi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reservasi',
            name='no_hp',
            field=models.CharField(max_length=14),
        ),
    ]
