# Generated by Django 4.2.6 on 2023-10-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservasi', '0004_alter_reservasi_durasi_baca'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservasi',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
    ]
