# Generated by Django 4.2.6 on 2023-10-25 10:54

from django.db import migrations

from django.core.management import call_command

def load_my_initial_data(apps, schema_editor):
    call_command("loaddata", "dataset_buku.json")


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0002_auto_20231025_1733'),
    ]

    operations = [
        migrations.RunPython(load_my_initial_data),
    ]
