# Generated by Django 4.2.6 on 2023-10-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0003_auto_20231025_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buku',
            name='isbn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
