# Generated by Django 4.2.6 on 2023-10-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buku', '0004_alter_buku_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='is_ready',
            field=models.BooleanField(default=True),
        ),
    ]
